name = "onenetly"
type = "webpack"
account_id = ""  # Your Cloudflare account ID
zone_id = ""     # Your Cloudflare zone ID
route = ""       # The route pattern your site will be served at
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
workers_dev = false
route = "example.com/*"  # Replace with your domain

[env.staging]
workers_dev = true
